### ISSUE TITLE
a small question about proof of Theorem 4

### ISSUE THREAD

**Issue by coraler** [balcilar/gnn-spectral-expressive-power#1]
About Theorem 4 Proposition 2, you have a assumption D=pI, then you can get L=I-A/p. Why? L=D-A=pI-A, isn't it? Or, you want to row noramlize? Can you give me some explanation? It's a great paper.

**Comment by balcilar** [comment]
Thanks for your attention to our paper.

The reason why we write laplacien by L=I-A/p for regular graph whose node degrees are equal to p is that we used normalized graph laplacien (e.g L=I − D^{−1/2} AD^{−1/2}) . Thus, if you use D=pI in the normalized graph laplacien, you can get L=I-A/p.

All our spectral analysis (frequency responses) are extracted with respect to the normalized graph laplacien, but not unnormalized laplacien ( which is L=D-A,  it is called combinatorial graph laplacien sometimes).

Hope this explanation works for you.

**Comment by coraler** [comment]
Thank you very much.
