### ISSUE TITLE
Python script for generating raw bandclass matrices

### ISSUE THREAD

**Issue by ShichangZh** [balcilar/gnn-spectral-expressive-power#2]
Thank you for the great work! I really liked the analysis in this paper and the comprehensive experiments on different datasets. For the bandclass experiment, could you please also public your python script for generating the raw matrices? I would like to generate a similar dataset but with smaller graph sizes for my work. Thanks.

**Comment by balcilar** [comment]
Thanks for your attention to our paper and code.
Great point actually. I will upload the bandclass dataset generation code as well in a week.
Sorry for my late, it is because of my busy schedule nowadays.

Thanks for your understanding.

**Comment by ShichangZh** [comment]
Sorry for bothering again. Did you get a chance to upload the bandclass data generation code?
I totally understand that you have a very busy schedule, so please take your time. I really appreciate that you can share your code for others to build their research on top of it.  

Thanks.

**Comment by balcilar** [comment]
Sorry for the late reply.
I just uploaded the bandclass dataset preparation script.
You can just launch the prepare_bandclass_dataset.py script directly.
Necessary parameters were hardcoded in the source file.
You can change it accordingly.
It will save the node features, adjacencies and the signal frequencies in the mat file.

anything else, please do not hesitate to contact me.

**Comment by ShichangZh** [comment]
Thank you for taking time to provide the script. I truly appreciate your help!
