### ISSUE TITLE
Python script for generating raw 2Dgrid graph and Filtering operation

### ISSUE THREAD

**Issue by ivam-he** [balcilar/gnn-spectral-expressive-power#3]
Thank you for the great work! I really liked the analysis in this paper. For the appendix I, could you please also public your python script for generating the 2Dgrid graph and the corresponding filtering process? I would like to add different filters，like band-rejection filter. Thanks.

**Comment by balcilar** [comment]
Thanks for your interest in this repo.
Unfortunately, I prepared it by Matlab script not Python.
I just uploaded the Matlab script to prepare the 2Dgrid graph dataset.
Hope it will help you.

**Comment by ivam-he** [comment]
That's great! Thanks!
